name: SwissBook
main: tk.mapzcraft.firesofhades.SwissBook.SwissBook
version: 0.2
commands:
  swissbook:
    description: SwissBook master command
    aliases: ['sb']
    usage: /<command> [function] <args[]>