name: SwissBook
main: tk.mapzcraft.firesofhades.SwissBook.SwissBook
version: 1.1
commands:
  swissbook:
    description: SwissBook master command
    aliases: ['sb']
    usage: /<command> [function] <args[]>
  manual:
    description: gives players a manual